spring:
  application:
    name: config-demo
  profiles:
    active: prod


build:
  id: ${ID}
  version: ${VERSION}}
  name: ${NAME}


  #BUILD_ID=4444;BUILD_NAME=NAME_TEST;BUILD_VERSION=1.0.0
  #ID=9999;NAME=NEW_NAME;VERSION=3.3.3.3
