spring:
  data:
    mongodb:
      #      uri: mongodb+srv://sriharsha:sriharsha@user-data.hu3yv9q.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      uri: ${MONGO_URI}
      database: ecom_user

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: sriharsha
#    password: sriharsha
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082


